# Generated by Django 5.0.14 on 2026-07-23 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='flagged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_flagged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='tools.tool'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='rental',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='rentals.rentalrequest'),
        ),
    ]
